const cardImages = {
  Clubs: {
    A: require('../assets/clubs/clubA.png'),
    2: require('../assets/clubs/club2.png'),
    3: require('../assets/clubs/club3.png'),
    4: require('../assets/clubs/club4.png'),
    5: require('../assets/clubs/club5.png'),
    6: require('../assets/clubs/club6.png'),
    7: require('../assets/clubs/club7.png'),
    8: require('../assets/clubs/club8.png'),
    9: require('../assets/clubs/club9.png'),
    10: require('../assets/clubs/club10.png'),
    J: require('../assets/clubs/clubJ.png'),
    K: require('../assets/clubs/clubK.png'),
    Q: require('../assets/clubs/clubQ.png'),
  },
  Diamonds: {
    A: require('../assets/diamonds/diamondA.png'),
    2: require('../assets/diamonds/diamond2.png'),
    3: require('../assets/diamonds/diamond3.png'),
    4: require('../assets/diamonds/diamond4.png'),
    5: require('../assets/diamonds/diamond5.png'),
    6: require('../assets/diamonds/diamond6.png'),
    7: require('../assets/diamonds/diamond7.png'),
    8: require('../assets/diamonds/diamond8.png'),
    9: require('../assets/diamonds/diamond9.png'),
    10: require('../assets/diamonds/diamond10.png'),
    J: require('../assets/diamonds/diamondJ.png'),
    K: require('../assets/diamonds/diamondK.png'),
    Q: require('../assets/diamonds/diamondQ.png'),
  },
  Hearts: {
    A: require('../assets/hearts/heartA.png'),
    2: require('../assets/hearts/heart2.png'),
    3: require('../assets/hearts/heart3.png'),
    4: require('../assets/hearts/heart4.png'),
    5: require('../assets/hearts/heart5.png'),
    6: require('../assets/hearts/heart6.png'),
    7: require('../assets/hearts/heart7.png'),
    8: require('../assets/hearts/heart8.png'),
    9: require('../assets/hearts/heart9.png'),
    10: require('../assets/hearts/heart10.png'),
    J: require('../assets/hearts/heartJ.png'),
    K: require('../assets/hearts/heartK.png'),
    Q: require('../assets/hearts/heartQ.png'),
  },
  Spades: {
    A: require('../assets/spades/spadeA.png'),
    2: require('../assets/spades/spade2.png'),
    3: require('../assets/spades/spade3.png'),
    4: require('../assets/spades/spade4.png'),
    5: require('../assets/spades/spade5.png'),
    6: require('../assets/spades/spade6.png'),
    7: require('../assets/spades/spade7.png'),
    8: require('../assets/spades/spade8.png'),
    9: require('../assets/spades/spade9.png'),
    10: require('../assets/spades/spade10.png'),
    J: require('../assets/spades/spadeJ.png'),
    K: require('../assets/spades/spadeK.png'),
    Q: require('../assets/spades/spadeQ.png'),
  },
  Joker: {
    Red: require('../assets/jokers/Joker_Red.png'),
    Black: require('../assets/jokers/Joker_Black.png'),
  },
};

export default cardImages;
